
#' Sample data from a multivariate distribution using the Metropolis-Hastings Algorithm using a cpp implementation.
#' The use of this function is recommended when the target density function is in the predefined set of densities in the function's API.
#' @param targetdensity This is the probability density function from which sampling will be done. This should be one of the supported values:
#' "Exponential"- Exponential distribution with lambda=1.
#' @param candidatedensity This is the candidate generation density to be used. This should be one of the supported values
#' @param numIter The number of samples to generate
#' @param initial_vec The staring vector for the algorithm
#' @param plot plot the values of x
#' @param sigma_matrix standard deviation matrix of the candidate generation density
#' @param seed seed for generation of random samples
#'
#' @return a matrix of sample vectors
#' @export
#'
#' @examples
cppmultivariatemh = function(targetdensity=c("Exponential"),  candidatedensity=c("Normal"),
                           numIter=1000, initial=0.0, plot=FALSE, sigma=1, seed = 1001L){
  candidatedensity = match.arg(candidatedensity)
  targetdensity = match.arg(targetdensity)
  #check sigma
  if(is.null(sigma)){
    stop('sigma must not be null')
  }
  if(sigma <= 0){
    stop("sigma must be positive")
  }
  #check target density
  if(is.null(targetdensity)){
    stop("Target density function must be provided")
  }

  #call the cpp function
  set.seed(seed)
  #assume normal candidate generation density
  x = NULL
  if(targetdensity == "Exponential"){
    x =   univariatemhexpnormalcpp(numIter, initial, sigma)
  }

  #plot if asked
  if(plot){
    plot(x, main='Samples generated by M-H algorithm')
    plot(density(x), main="Estimated Target Density Distribution",
         xlab = "Samples", ylab="Target Density")
  }
  return (x)
}
