# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_RMetropolisHastings_rcpp_hello`)
}

univariatemhnormalcpp <- function(targetDensity, numIter, initial, sigma) {
    .Call(`_RMetropolisHastings_univariatemhnormalcpp`, targetDensity, numIter, initial, sigma)
}

