# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_RMetropolisHastings_rcpp_hello`)
}

#' C++ function to generate a probability from a univariate exponential density function
#' @param x This is the x value
targetDensityUnivarExp <- function(x) {
    .Call(`_RMetropolisHastings_targetDensityUnivarExp`, x)
}

#' C++ function to generate samples using univariate normal candidate density
#' @param numIter This is the number of iterations to run the algorithm
#' @param initial This is the starting value for the markov chain
#' @param sigma This is the standard deviation for candidate generating univariate normal distribution.
univariatemhexpnormalcpp <- function(numIter, initial, sigma) {
    .Call(`_RMetropolisHastings_univariatemhexpnormalcpp`, numIter, initial, sigma)
}

