
#' Sample data from a univariate distribution using the Metropolis-Hastings Algorithm
#'
#' @param targetdensity This is the probability density function from which sampling will be done. This should be a function of x.
#' @param candidatedensity This is the candidate generation density to be used
#' @param numIter The number of samples to generate
#' @param initial The staring value for the algorithm
#' @param plot plot the values of x
#' @param sigma standard deviation of the candidate generation density
#' @param seed seed for generation of random samples
#'
#' @return a vector of samples
#' @export
#'
#' @examples
runivariatemh = function(targetdensity,  candidatedensity=c("Normal"),
                         numIter=1000, initial=0.0, plot=FALSE, sigma=NUL, seed = 1001L){
  candidatedensity = match.arg(candidatedensity)
  #check sigma
  if(is.null(sigma)){
    stop('sigma must not be null')
  }
  if(sigma <= 0){
    stop("sigma must be positive")
  }
  #check target density
  if(is.null(targetdensity)){
    stop("Target density function must be provided")
  }

  # initialize the x vector to capture the generated samples
  x = rep(initial, numIter)
  set.seed(seed)
  #build the markov chain
  for(i in 2:numIter){
    # generate a  possible move in the markov chain
    nextVal = rnorm(1, x[i-1], sigma)

    #compute the acceptance probability
    #this is a special case because the candidate is symmetric
    prevDensity = targetdensity(x[i-1])
    if(prevDensity == 0){
      stop(paste('invalid value (0) returned by target density for x = ', x[i-1]))
    }
    prob = min(1, targetdensity(nextVal) / prevDensity)
    u = runif(1)

    #accept the sample with 'prob' probability
    if(u <= prob){
      x[i] = nextVal
    }
    else{
      x[i] = x[i-1]
    }
  }

  #plot if asked
  if(plot){
    plot(x, main='Samples generated by M-H algorithm')
    plot(density(x), main="Estimated Target Density Distribution",
         xlab = "Samples", ylab="Target Density")
  }
  return (x)
}
